"""ClinVision synthetic-only contract utilities.

The package is intentionally import-light: no dataset, model, GPU, network, or
clinical runtime dependency is imported at module load time.
"""

from .contracts import (
    ArtifactPolicy,
    ArtifactManifestEntry,
    BaselineConfig,
    BiomedCLIPRetrievalRequest,
    BLIP2GenerationRequest,
    DatasetProvenance,
    ErrorCode,
    ErrorTaxonomyEntry,
    EvaluationReportContract,
    LicenceLedgerEntry,
    ManifestRecord,
    MetricRecord,
    PEFTConfig,
    SafeInferenceRequest,
    SplitRecord,
    ValidationIssue,
    ValidationResult,
    check_artifact_path,
    validate_artifact_manifest,
    validate_baseline_config,
    validate_biomedclip_request,
    validate_blip2_request,
    validate_ledger,
    validate_manifest,
    validate_metrics,
    validate_peft_config,
    validate_report_contract,
    validate_safe_inference_request,
    validate_split_contract,
    validate_train_eval_overlap,
)
from .pipeline import validate_synthetic_workflow
from .runner import SyntheticRunResult, run_synthetic_contract_pass
from .synthetic import SyntheticRecords, build_synthetic_records

__all__ = [
    "ArtifactPolicy",
    "ArtifactManifestEntry",
    "BaselineConfig",
    "BiomedCLIPRetrievalRequest",
    "BLIP2GenerationRequest",
    "DatasetProvenance",
    "ErrorCode",
    "ErrorTaxonomyEntry",
    "EvaluationReportContract",
    "LicenceLedgerEntry",
    "ManifestRecord",
    "MetricRecord",
    "PEFTConfig",
    "SafeInferenceRequest",
    "SplitRecord",
    "ValidationIssue",
    "ValidationResult",
    "check_artifact_path",
    "validate_artifact_manifest",
    "validate_baseline_config",
    "validate_biomedclip_request",
    "validate_blip2_request",
    "validate_ledger",
    "validate_manifest",
    "validate_metrics",
    "validate_peft_config",
    "validate_report_contract",
    "validate_safe_inference_request",
    "validate_split_contract",
    "validate_train_eval_overlap",
    "SyntheticRecords",
    "SyntheticRunResult",
    "build_synthetic_records",
    "run_synthetic_contract_pass",
    "validate_synthetic_workflow",
]
